# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - sinarmas-mini-e-commerce

on:
  push:
    branches:
      - 1.4-refactor-structure-db

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sinarmas-mini-e-commerce'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0eeb7bb5dc574a50aa6928246860e394 }}
        package: '${{ github.workspace }}/target/*.jar'